import { useContext, useEffect, useState } from "react";
import axios from "axios";
import LoginContext from "../LoginContext";
import Select from "react-select";
import LinkIcon from "./LinkIcon";

function Tracks() {
  const loginContext = useContext(LoginContext);
  const token = localStorage.getItem("token");
  const userInfoJSON = loginContext.userInfoJSON;
  const [tracksJSON, setTracksJSON] = useState([]);
  const timeRangeOptions = [
    { value: "short_term", label: "Past 4 Weeks" },
    { value: "medium_term", label: "Past 6 Months" },
    { value: "long_term", label: "All Time" },
  ];
  const [timeRange, setTimeRange] = useState(timeRangeOptions[0]);
  const [playlistJSON, setPlaylistJSON] = useState({});
  const [isGenerated, setIsGenerated] = useState(false);

  const selectStyle = {
    control: (styles) => ({
      ...styles,
      backgroundColor: "#1b1a1b",
      borderRadius: "0.375rem",
      borderColor: "#ffffff1a",
    }),
    option: (styles) => ({ ...styles, color: "white", backgroundColor: "" }),
    singleValue: (styles) => ({ ...styles, color: "white" }),
    container: (styles) => ({ ...styles, width: "12rem" }),
    menu: (styles) => ({ ...styles, backgroundColor: "#252526" }),
  };

  useEffect(() => {
    async function fetchTopTracks() {
      const { data } = await axios.get(
        "https://api.spotify.com/v1/me/top/tracks",
        {
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json",
          },
          params: {
            time_range: timeRange["value"],
            limit: 50,
            offset: 0,
          },
        },
      );
      setTracksJSON(data.items);
    }
    fetchTopTracks();

    function getNewToken() {
      window.location.href = loginContext.AUTH_URL;
      const hash = window.location.hash;
      let token = hash;
      window.location.hash = "";
      return token;
    }

    axios.interceptors.response.use(null, async (error) => {
      if (error.response.status === 401) {
        const newToken = await getNewToken();
        window.localStorage.setItem("token", newToken);
      }

      return Promise.reject(error);
    });
  }, [timeRange]);

  function handleTimeRangeChange(selected) {
    setTimeRange(selected);
  }

  async function generatePlaylist() {
    const date = new Date();
    let day = String(date.getDate()).padStart(2, "0");
    let month = String(date.getMonth() + 1).padStart(2, "0");
    let year = String(date.getFullYear()).slice(2);

    let playlistData = JSON.stringify({
      name: `${userInfoJSON.display_name}'s Top Tracks, ${day}/${month}/${year}`,
      description: `A playlist generated by Statify (https://statify-app.vercel.app), based on ${
        userInfoJSON.display_name
      }'s top tracks in the past ${timeRange[
        "label"
      ].toLowerCase()}. Happy jamming!`,
      public: true,
    });

    let playlistConfig = {
      method: "post",
      maxBodyLength: Infinity,
      url: `https://api.spotify.com/v1/users/${userInfoJSON.id}/playlists`,
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      data: playlistData,
    };

    const { data } = await axios.request(playlistConfig);
    setPlaylistJSON(data);

    let trackURIs = "";
    tracksJSON.map((track) => {
      trackURIs += track.uri + ",";
    });
    trackURIs = trackURIs.slice(0, -1);

    let tracksData = {
      uris: trackURIs,
      position: 0,
    };

    let tracksConfig = {
      method: "post",
      maxBodyLength: Infinity,
      url: `https://api.spotify.com/v1/playlists/${data.id}/tracks`,
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      params: tracksData,
    };

    await axios.request(tracksConfig);
    setIsGenerated(true);
  }

  return (
    <>
      <div className="flex flex-col items-center justify-center gap-10 py-10">
        <h1 className="text-2xl">Top Tracks, {timeRange["label"]}</h1>
        <div className="flex flex-col items-center justify-center gap-5">
          <Select
            onChange={handleTimeRangeChange}
            options={timeRangeOptions}
            placeholder={"Select time range"}
            styles={selectStyle}
          />
          {!isGenerated ? (
            <button
              className="rounded-md bg-green-600 px-5 py-1 font-extralight text-white hover:bg-green-700 duration-100 ease-in"
              onClick={generatePlaylist}
            >
              Generate playlist
            </button>
          ) : (
            <a
              href={playlistJSON.external_urls["spotify"]}
              target="_blank"
              rel="noreferrer"
            >
              <button className="rounded-md bg-sky-600 px-5 py-1 font-extralight text-white hover:bg-sky-700 duration-100 ease-in">
                View playlist
              </button>
            </a>
          )}
        </div>
        <div className="flex flex-col">
          {tracksJSON.map((track, index) => (
            <div
              key={index}
              className=" bg-bg-secondary relative mx-5 flex items-center justify-between border-[1px] border-b-0 border-[#ffffff1a] px-5 py-5 first:rounded-t-md last:rounded-b-md last:border-b-[1px]"
            >
              <div className="flex items-center justify-center gap-2">
                <h1 className="text-2xl">{index + 1}.</h1>
                <img
                  className="h-[15vh] w-[15vw] object-scale-down"
                  src={track.album.images[0]["url"]}
                ></img>
                <div className="flex-col">
                  <div className="flex gap-2">
                    <h1 className="text-xl">
                      {track.name.length > 24
                        ? track.name.substring(0, 24) + "..."
                        : track.name}
                    </h1>
                  </div>
                  <div>
                    {track.artists.map((artist, index) => (
                      <div key={index}>{artist.name}</div>
                    ))}
                  </div>
                </div>
              </div>
              <LinkIcon link={track.external_urls["spotify"]} />
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
export default Tracks;
